version: '3'
services:
  web:
    image: web_app1:latest
    ports:
      - "5000:5000"
    volumes:
      - ./templates:/app/templates
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: newdb
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: Ubuntu@123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
